// SPDX-License-Identifier: MIT
// Auto-generated by tools/gen_class_sizes.py from the format notes
// DO NOT EDIT MANUALLY — regenerate with `python tools/gen_class_sizes.py`

#ifndef VC_CLASS_SIZES_H
#define VC_CLASS_SIZES_H

// Byte-direct class sizes extracted from the on-disk format via byte-direct format analysis.
// Use static_assert(sizeof(VC_X) == VC_X_SIZE) in implementations to enforce.

namespace xfiles {
namespace vc {

// Class | size
constexpr unsigned int VCCHARACTER_SIZE = 0x2c;  //   44 bytes
constexpr unsigned int VCPLAYER_SIZE = 0x2c;  //   44 bytes
constexpr unsigned int VCASSETCATEGORY_SIZE = 0x30;  //   48 bytes
constexpr unsigned int VCENABLED_SIZE = 0x30;  //   48 bytes
constexpr unsigned int VCIDEAMAP_SIZE = 0x30;  //   48 bytes
constexpr unsigned int VCSTDACTION_SIZE = 0x34;  //   52 bytes
constexpr unsigned int VCNAV_SIZE = 0x38;  //   56 bytes
constexpr unsigned int VCSTRING_SIZE = 0x38;  //   56 bytes
constexpr unsigned int VCCURSOR_SIZE = 0x3c;  //   60 bytes
constexpr unsigned int VCVIEW_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCASSETREF_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCACTIONICON_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCEMOTIONICON_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCEVIDENCEICON_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCIDEAICON_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCINVENTORY_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCVARIABLE_SIZE = 0x44;  //   68 bytes
constexpr unsigned int VCNAME_SIZE = 0x48;  //   72 bytes
constexpr unsigned int VCCONVERSATION_SIZE = 0x48;  //   72 bytes
constexpr unsigned int VCHOTSPOT_SIZE = 0x48;  //   72 bytes
constexpr unsigned int VCDEFAULTCURSORS_SIZE = 0x48;  //   72 bytes
constexpr unsigned int VCDEFAULTHOTSPOTS_SIZE = 0x48;  //   72 bytes
constexpr unsigned int VCEXPLORABLE_SIZE = 0x4c;  //   76 bytes
constexpr unsigned int VCINTERFACEITEM_SIZE = 0x54;  //   84 bytes
constexpr unsigned int VCCHARVIEW_SIZE = 0x5c;  //   92 bytes
constexpr unsigned int VCCHARVIEWLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCCONVERSATIONLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCNAV_LIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCASSETREFLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCEXPLORABLELIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCHOTSPOTLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCSTDHOTSPOTLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCACTIONLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCBLOB_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCIDEAMAPLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCTRIGGERLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCSTDACTIONLIST_SIZE = 0x64;  //  100 bytes
constexpr unsigned int VCACTION_SIZE = 0x6c;  //  108 bytes
constexpr unsigned int VCIFACELAYOUT_SIZE = 0x6c;  //  108 bytes
constexpr unsigned int VCNODE_SIZE = 0x70;  //  112 bytes
constexpr unsigned int VCLOCATON_SIZE = 0x78;  //  120 bytes
constexpr unsigned int VCEMAIL_SIZE = 0x78;  //  120 bytes
constexpr unsigned int VCEMAILREAD_SIZE = 0x78;  //  120 bytes
constexpr unsigned int VCEMAILPENDING_SIZE = 0x78;  //  120 bytes
constexpr unsigned int VCVIEWPOINT_SIZE = 0x7c;  //  124 bytes
constexpr unsigned int VCCONVERSATIONHISTORY_SIZE = 0x80;  //  128 bytes
constexpr unsigned int VCPDANOTES_SIZE = 0x80;  //  128 bytes
constexpr unsigned int VCPHOTO_SIZE = 0x98;  //  152 bytes
constexpr unsigned int VCTITLE_SIZE = 0xa8;  //  168 bytes
constexpr unsigned int VCTRIGGER_SIZE = 0xec;  //  236 bytes
constexpr unsigned int VCGAMESTATE_SIZE = 0x1ac;  //  428 bytes

constexpr unsigned int VC_CLASS_COUNT = 51;

// Verification helper — use in unit tests via SIZE_OF_VC(VCEmail) == VC_EMAIL_SIZE
#define SIZE_OF_VC(cls) sizeof(::xfiles::vc::cls)

}  // namespace vc
}  // namespace xfiles

#endif  // VC_CLASS_SIZES_H
